name: due_tocoffee
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1




dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  camera: ^0.11.1
  image: ^4.5.4        # ⬅️ Downgraded
  logger: ^2.0.2
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.5
  geolocator: ^14.0.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.2
  google_sign_in: ^6.1.7
  intl: ^0.20.2 
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  cloud_functions: ^5.4.0
  url_launcher: ^6.1.10
  android_intent_plus: ^4.0.0
  flutter_inappwebview: ^6.0.0-beta.24
  app_links: ^3.0.0
  shared_preferences: ^2.0.8
  flutter_local_notifications: ^19.2.0
  firebase_messaging: ^15.2.5
  flutter_dotenv: ^5.1.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/military.jpg
    - assets/images/coffee_Logo.png
  
